# Generated by Django 4.2.30 on 2026-05-23 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('emprunt', 'Emprunt'), ('retour', 'Retour'), ('penalite', 'Pénalité')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-date_action'],
            },
        ),
    ]
