# Generated by Django 4.2.30 on 2026-05-23 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_emprunt_jours', models.IntegerField(default=7, help_text="Durée d'emprunt par défaut en jours")),
                ('tarif_penalite_journalier', models.IntegerField(default=100, help_text='Tarif journalier de pénalité en FCFA')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration du système',
                'verbose_name_plural': 'Configurations du système',
            },
        ),
    ]
