# Generated by Django 4.2.30 on 2026-05-21 22:03

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ine',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.users.models.validate_ine]),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
