# Generated by Django 4.2 on 2026-05-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('isbn', models.CharField(help_text='Code ISBN à 13 chiffres', max_length=13, unique=True)),
                ('editeur', models.CharField(blank=True, max_length=100, null=True)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('nombre_exemplaires', models.IntegerField(default=1)),
                ('nombre_disponibles', models.IntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.categorie')),
            ],
            options={
                'verbose_name': 'Ouvrage',
                'verbose_name_plural': 'Ouvrages',
                'ordering': ['titre'],
            },
        ),
    ]
