# Generated by Django 4.2.30 on 2026-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_categorie_options_alter_ouvrage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='annee_edition',
            field=models.IntegerField(blank=True, null=True, verbose_name="Année d'édition"),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='maison_edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Maison d'édition"),
        ),
    ]
