# Generated by Django 4.2.30 on 2026-05-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jours_retard', models.IntegerField()),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('motif_annulation', models.TextField(blank=True, null=True)),
                ('emprunt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalite', to='loans.emprunt')),
            ],
            options={
                'ordering': ['-date_calcul'],
            },
        ),
    ]
