# Generated by Django 4.2.30 on 2026-05-23 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_categorie_options_alter_ouvrage_options_and_more'),
        ('loans', '0002_penalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('notifie', 'Notifié'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.ouvrage')),
            ],
            options={
                'ordering': ['date_reservation'],
            },
        ),
    ]
